import type { AppConfig } from './types'

export const appConfig: AppConfig = {
  theme: 'default',
  wallpaper: '/wallpapers/default.png',
  searchEngines: [
    {
      id: 'bing',
      label: 'Bing',
      url: 'https://www.bing.com/search?q={query}',
    },
    {
      id: 'github',
      label: 'GitHub',
      url: 'https://github.com/search?q={query}&type=repositories',
    },
    {
      id: 'bilibili',
      label: 'Bilibili',
      url: 'https://search.bilibili.com/all?keyword={query}',
    },
    {
      id: 'chatgpt',
      label: 'ChatGPT',
      url: 'https://chatgpt.com/?q={query}',
    },
    {
      id: 'deepseek',
      label: 'DeepSeek',
      url: 'https://chat.deepseek.com/?q={query}',
      copyQueryToClipboard: true,
    },
    {
      id: 'google',
      label: 'Google',
      url: 'https://www.google.com/search?q={query}',
    },
  ],
  widgets: [
    {
      id: 'links',
      type: 'links.grid',
      title: 'Links',
      layout: { x: 0, y: 0, w: 4, h: 3, minW: 3, minH: 2 },
      links: [
        { id: 'chatgpt', label: 'ChatGPT', href: 'https://chatgpt.com', category: 'AI' },
        { id: 'deepseek', label: 'DeepSeek', href: 'https://chat.deepseek.com', category: 'AI' },
        { id: 'github', label: 'GitHub', href: 'https://github.com', category: 'Dev' },
        { id: 'vercel', label: 'Vercel', href: 'https://vercel.com', category: 'Dev' },
        { id: 'mdn', label: 'MDN', href: 'https://developer.mozilla.org', category: 'Dev' },
        { id: 'bilibili', label: 'Bilibili', href: 'https://www.bilibili.com', category: 'Media' },
        { id: 'youtube', label: 'YouTube', href: 'https://www.youtube.com', category: 'Media' },
        { id: 'gmail', label: 'Gmail', href: 'https://mail.google.com', category: 'Tools' },
        { id: 'notion', label: 'Notion', href: 'https://www.notion.so', category: 'Tools' },
        { id: 'bing', label: 'Bing', href: 'https://www.bing.com', category: 'Search' },
      ],
    },
    {
      id: 'github-heatmap',
      type: 'github.heatmap',
      title: 'GitHub',
      layout: { x: 4, y: 0, w: 5, h: 3, minW: 4, minH: 2 },
      endpoint: '/api/github/contributions',
      refreshIntervalMs: 30 * 60 * 1000,
    },
    {
      id: 'school-today',
      type: 'school.today',
      title: 'Today',
      layout: { x: 9, y: 0, w: 3, h: 3, minW: 3, minH: 2 },
      endpoint: '/api/school/today',
      refreshIntervalMs: 10 * 60 * 1000,
    },
    {
      id: 'codex-usage',
      type: 'codex.usage',
      title: 'Codex',
      layout: { x: 0, y: 3, w: 4, h: 3, minW: 3, minH: 2 },
      endpoint: '/api/codex/usage/today',
      refreshIntervalMs: 10 * 60 * 1000,
    },
    {
      id: 'automation-digest',
      type: 'automation.digest',
      title: 'Automation',
      layout: { x: 4, y: 3, w: 5, h: 3, minW: 4, minH: 2 },
      endpoint: '/api/automation/digest',
      refreshIntervalMs: 5 * 60 * 1000,
    },
    {
      id: 'scripts-status',
      type: 'scripts.status',
      title: 'Scripts',
      layout: { x: 9, y: 3, w: 3, h: 3, minW: 3, minH: 2 },
      endpoint: '/api/scripts/status',
      refreshIntervalMs: 30 * 1000,
    },
    {
      id: 'notifications',
      type: 'notifications.center',
      title: 'Notifications',
      layout: { x: 0, y: 6, w: 4, h: 3, minW: 3, minH: 2 },
      endpoint: '/api/notifications',
      refreshIntervalMs: 2 * 60 * 1000,
    },
    {
      id: 'homework-due',
      type: 'homework.due',
      title: 'Homework',
      layout: { x: 4, y: 6, w: 4, h: 3, minW: 3, minH: 2 },
      endpoint: '/api/homework/due',
      refreshIntervalMs: 10 * 60 * 1000,
    },
    {
      id: 'sticky-note',
      type: 'notes.sticky',
      title: 'Note',
      layout: { x: 8, y: 6, w: 4, h: 3, minW: 3, minH: 2 },
    },
    {
      id: 'weather',
      type: 'weather.summary',
      title: 'Weather',
      layout: { x: 0, y: 9, w: 3, h: 3, minW: 3, minH: 2 },
    },
    {
      id: 'mail-digest',
      type: 'mail.digest',
      title: 'Mail',
      layout: { x: 3, y: 9, w: 4, h: 3, minW: 3, minH: 2 },
    },
    {
      id: 'important-info',
      type: 'important.info',
      title: 'Important',
      layout: { x: 7, y: 9, w: 5, h: 3, minW: 3, minH: 2 },
    },
  ],
}
